import logging
import os
from pathlib import Path
from io import BytesIO
import base64

from aiogram import Bot, Dispatcher, F
from aiogram.types import Message, FSInputFile
from aiogram.enums import ParseMode
from aiogram.types import BufferedInputFile
from aiogram.client.session.aiohttp import AiohttpSession
from aiogram.webhook.aiohttp_server import SimpleRequestHandler, setup_application
from aiohttp import web
import pandas as pd

# === Config ===
API_TOKEN = os.getenv("BOT_TOKEN")
BASE_WEBHOOK_URL = os.getenv("BASE_WEBHOOK_URL")
WEBHOOK_PATH = "/webhook"
WEBHOOK_URL = BASE_WEBHOOK_URL + WEBHOOK_PATH

# === Новый шаблон XLSX в base64 ===
EXCEL_TEMPLATE_BASE64 = """UEsDBBQABgAIAAAAIQBi7p1oXgEAAJAEAAATAAgCW0NvbnRlbnRfVHlwZXNdLnhtbCCiBAIooAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACslMtOwzAQRfdI/EPkLUrcskAINe2CxxIqUT7AxJPGqmNbnmlp/56J+xBCoRVqN7ESz9x7MvHNaLJubbaCiMa7UgyLgcjAVV4bNy/Fx+wlvxcZknJaWe+gFBtAMRlfX41mmwCYcbfDUjRE4UFKrBpoFRY+gOOd2sdWEd/GuQyqWqg5yNvB4E5W3hE4yqnTEOPRE9RqaSl7XvPjLUkEiyJ73BZ2XqVQIVhTKWJSuXL6l0u+cyi4M9VgYwLeMIaQvQ7dzt8Gu743Hk00GrKpivSqWsaQayu/fFx8er8ojov0UPq6NhVoXy1bnkCBIYLS2ABQa4u0Fq0ybs99xD8Vo0zL8MIg3fsl4RMcxN8bZLqej5BkThgibSzgpceeRE85NyqCfqfIybg4wE/tYxx8bqbRB+QERfj/FPYR6brzwEIQycAhJH2H7eDI6Tt77NDlW4Pu8ZbpfzL+BgAA//8DAFBLAwQUAAYACAAAACEAtVUwI/QAAABMAgAACwAIAl9yZWxzLy5yZWxzIKIEAiigAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKySTU/DMAyG70j8h8j31d2QEEJLd0FIuyFUfoBJ3A+1jaMkG92/JxwQVBqDA0d/vX78ytvdPI3qyCH24jSsixIUOyO2d62Gl/pxdQcqJnKWRnGs4cQRdtX11faZR0p5KHa9jyqruKihS8nfI0bT8USxEM8uVxoJE6UchhY9mYFaxk1Z3mL4rgHVQlPtrYawtzeg6pPPm3/XlqbpDT+IOUzs0pkVyHNiZ9mufMhsIfX5GlVTaDlpsGKecjoieV9kbMDzRJu/E/18LU6cyFIiNBL4Ms9HxyWg9X9atDTxy515xDcJw6vI8MmCix+o3gEAAP//AwBQSwMEFAAGAAgAAAAhAGilFD7HAgAAUwYAAA8AAAB4bC93b3JrYm9vay54bWykVV1vmzAUfZ+0/4D8TowJYRkqqdIk1SptU7V+aU+VAyZ4MZjZpiGr+t93DSFZm5euReCv6xyfe++5zslpUwjngSnNZRkjMvCQw8pEprxcxejm+twdI0cbWqZUyJLFaMs0Op18/HCykWq9lHLtAECpY5QbU0UY6yRnBdUDWbESLJlUBTUwVSusK8VoqnPGTCGw73khLigvUYcQqddgyCzjCZvLpC5YaToQxQQ1QF/nvNI9WpG8Bq6gal1XbiKLCiCWXHCzbUGRUyTRxaqUii4FuN2QkdMoeEP4iAeN358EpqOjCp4oqWVmBgCNO9JH/hMPE/IsBM1xDF6HFGDFHrjN4Z6VCt/IKtxjhQcw4r0bjYC0Wq1EELw3oo323Hw0Ocm4YLeddB1aVd9pYTMlkCOoNouUG5bG6BNM5YYdFgLkqLo6q7kAK/FGhCA82cv5Ujkpy2gtzDUIuYeHjX7g+6HdCcKYCsNUSQ2bydKADnd+vVdzLfYsl6Bw5wf7XXPFoLBAX+ArtDSJ6FJfUpM7tRIxwjcanMdpwY3aDpZScb3mJd5CsbJmkMIM/+zGcxgPhEyo4H9YigUtZEpxpeQvlhiNdV5nmWCukhvtNlo0+B9t0+NC+g9108SGDEPMOr+68cv4gXsq6hV8aZQD44v5V8jiFX2AnIJy0l3JX9ikDe/LREXk/nE6Hc4WZ8OFG8y8sesHwdidns8Dl4y84Zm38IfhyHsCZ1QYJZLWJt/JxULHKABtHJm+0aa3EC+qeXqg8ejtHtf2L5re9mQdthfjLWcbfRCWnTrNHS9TuWk92vbj8Rj827SGO56aPEbDEND6tS+Mr3Jg65OhXYTisaxi9IzNvGNzDo9rm2ds8D902usXaLW9U7Ylc2WvZAL3vO3bAEOJRPYMdZG21QESARP8DCSUQInYrt3oByPyuU1x/38w+QsAAP//AwBQSwMEFAAGAAgAAAAhAIE+lJfzAAAAugIAABoACAF4bC9fcmVscy93b3JrYm9vay54bWwucmVscyCiBAEooAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKxSTUvEMBC9C/6HMHebdhUR2XQvIuxV6w8IybQp2yYhM3703xsqul1Y1ksvA2+Gee/Nx3b3NQ7iAxP1wSuoihIEehNs7zsFb83zzQMIYu2tHoJHBRMS7Orrq+0LDppzE7k+ksgsnhQ45vgoJRmHo6YiRPS50oY0as4wdTJqc9Adyk1Z3su05ID6hFPsrYK0t7cgmilm5f+5Q9v2Bp+CeR/R8xkJSTwNeQDR6NQhK/jBRfYI8rz8Zk15zmvBo/oM5RyrSx6qNT18hnQgh8hHH38pknPlopm7Ve/hdEL7yim/2/Isy/TvZuTJx9XfAAAA//8DAFBLAwQUAAYACAAAACEAPC913RsEAABKDgAAGAAAAHhsL3dvcmtzaGVldHMvc2hlZXQxLnhtbJyVXW/aMBSG7yftP0S+bxKbjwICqm5Vtd5N+741jgGrccxsU6im/fceO3GSqlPqFUFsEt73HJ/z2CyvzrJMHrg2QlUrhNMcJbxiqhDVboW+f7u9mKHEWFoVtFQVX6FHbtDV+v275Unpe7Pn3CbgUJkV2lt7WGSZYXsuqUnVgVfwZKu0pBa+6l1mDprTwotkmZE8n2aSigrVDgsd46G2W8H4jWJHyStbm2heUgv5m704mOAmWYydpPr+eLhgSh7AYiNKYR+9KUokW9ztKqXppoR1n/GYsuSs4U3gMwph/P0XkaRgWhm1tSk4Z3XOL5c/z+YZZa3Ty/VH2eBxpvmDcA3srMjbUsKT1ot0ZqM3mk1bM1cuvTiKYoX+5M3rAkbsLnl3Cc/+ovWyENBht6pE8+0KXePF9QeMsvXSA/RD8JPpzRNLN195yZnlEASjxPG5Uere/fAObuVgafwPnKX5HUx/3d5416y1XS+7eQhx6zH+rJMNNfyjKn+Kwu4hDmyXgm/psbTdzVk6G5F8hMmkffhFnT5xsdtbkMBdD82ieLzhhgHFkFxK3MqYKiEgXBMp3G4ECOm5Xk0dj+TpqPVmR2OVDJk0+loJzfNKGE+NkqR4Os6nLqkBITTKC2FshHg6KBg3AhhDpMu4HCERHwrGEGoWlSMk5IUwBuE4nUYs7rIRwhiEk16vBsoCh6APCWNblqhc540QxiC8jMrVkVU3HyadtCNrIFvcguP2QdN/aNCQJBCDe8jgqCXiwIybdLTFZRrwwR0/eB7XE7eR6gp1BJF5Osy3o7kWdfSQ8WuiAA7uyCGw2KF6BmJwhwyZxNUzMIN70MxeSZEEXNzk/7YTCbS4SUtL5DnTHjTPsBnugStdfTr1gIk92AIwpHfg5HHAuKOvjtsDBkdqAzfkGTcxRyoJ9LhJqO8ksr4BI9LD6J/kZf6/4wkAAP//AAAA//9s1NtOg0AQBuBXIfsABdbWItmSYLG2ak9q6+GOrJv0ChuWVH17t8aEzMx/RzYfM+wcMP7gXFfVXV2Y9vMraicqVZE/1o0PT7nOVPSdDmubf/xUzlvXdBOVDLQqjD3b8oz/XgnnPpyeijQz8akwsf0n14BcUTKVRCeUVJIwcQPy0BgzkCal5BYQKuZSXFCxkGJIxR3Ioim5B4TleZBkRIMspbikYiXFmIq1FKzBGylYf7egNax7j+C+rGpPIAojz4CwmuwAYUXZg29hUV4AYVFeQSJW2zdA2EC+A8JGpQRLqFmmEm1hP09xWP2wsv2/4BcAAP//AAAA//+yKUhMT/VNLErPzCtWyElNK7FVMtAzV1IoykzPgLFL8gvAoqZKCkn5JSX5uTBeRmpiSmoRiGespJCWn18C4+jb2eiX5xdlF2ekppbYAQAAAP//AwBQSwMEFAAGAAgAAAAhAMKH2/J9BgAA1xsAABMAAAB4bC90aGVtZS90aGVtZTEueG1s7FlLbxs3EL4X6H8g9p7oYUm2jMiBJUtxmzgxbCVFjtSK2mXEXS5Iyo5uRXIsUKBoWvRSoLceirYBEqCX9Ne4TdGmQP5Ch+RKWlp0bCcG+rIOtsT9OO8ZznCvXX+YMHRAhKQ8bQWVq+UAkTTkQ5pGreBuv3dlLUBS4XSIGU9JK5gSGVzfeP+9a3hdxSQhCPanch23glipbL1UkiEsY3mVZySFZyMuEqzgp4hKQ4EPgW7CStVyuVFKME0DlOIEyN4ZjWhIUN+QhKer6AqqlivlYGPGqMuAW6qkXgiZ2NdsiLv7+L7huKLRcio7TKADzFoB8B/ywz55qALEsFTwoBWUzScobVwr4fV8E1Mn7C3s65lPvi/fMBxXDU8RDeZMK71ac3VrTt8AmFrGdbvdTrcyp2cAOAxBaytLkWatt1Zpz2gWQPbrMu1OuV6uufgC/ZUlmZvtdrvezGWxRA3Ifq0t4dfKjdpm1cEbkMXXl/C19man03DwBmTxjSV8b7XZqLl4A4oZTcdLaO3QXi+nPoeMONv2wtcAvlbO4QsURMM80jSLEU/VWeIuwQ+46AFYb2JY0RSpaUZGOIRI7+BkICjWzPA6wYUndimUS0uaL5KhoJlqBR9mGLJmQe/1i+9fv3iGXr94evTo+dGjn44ePz569KOl5WzcxmlU3Pjq28/+/Ppj9Mezb149+cKPl0X8rz988svPn/uBkE0LiV5++fS3509ffvXp79898cA3BR4U4X2aEIluk0O0xxPQzRjGlZwMxPl29GNMnR04Btoe0l0VO8DbU8x8uDZxjXdPQCHxAW9MHjiy7sdioqiH8804cYA7nLM2F14D3NS8ChbuT9LIz1xMirg9jA98vDs4dVzbnWRQTWdB6di+ExNHzF2GU4UjkhKF9DM+JsSj3X1KHbvu0FBwyUcK3aeojanXJH06cAJpsWmbJuCXqU9ncLVjm517qM2ZT+stcuAiISEw8wjfJ8wx4w08UTjxkezjhBUNfgur2Cfk/lSERVxXKvB0RBhH3SGR0rfnjgB9C06/iaF2ed2+w6aJixSKjn00b2HOi8gtPu7EOMm8MtM0LmI/kGMIUYx2ufLBd7ibIfo3+AGnJ7r7HiWOu08vBHdp5Ii0CBD9ZCI8vrxBuJuPUzbCxFQZKO9OpU5o+qayzSjU7cuyPTvHNuEQ8yXP9rFifRLuX1iit/Ak3SWQFctH1GWFvqzQwX++Qp+UyxdflxelGKr0ou82XXhypiZ8RBnbV1NGbknTh0s4jIY9WDTDgpke5wNaFsPXvP13cJHAZg8SXH1EVbwf4wx6+IoZSyOZk44kyriEOdIsmwGYHKNtxlgKbbyZQut6PrFVRGK1w4d2eaU4h87JmKk0MnPvjNGKJnBWZiur78asYqU60WyuahUjmimQjmpzlcGfy6rB4tya0OUg6I3Ayg0Y6LXsMPtgRoba7nZGn7lFs75QF8kYD0nuI633so8qxkmzWJmFkcdHeqY8xUcFbk1N9h24ncVJRXa1E9jNvPcuXpoN0gsv6Rw+lo4sLSYnS9FhK2jWq/UAhThrBSMYm+FrkoHXpW4sMYvgfipUwob9qclswnXhzaY/LCtwK2LtvqSwUwcyIdUWlrENDfMoDwGWmiHfyF+tg1kvSgEb6W8hxcoaBMPfJgXY0XUtGY1IqIrOLqyYOxADyEspnygi9uPhIRqwidjD4H4dqqDPkEq4/TAVQf+AazttbfPILc550hUvywzOrmOWxTgvtzpFZ5ls4SaP5zKYX1ZaIx7o5pXdKHd+VUzKX5AqxTD+n6mizxO4jlgZag+EcJssMNL52gq4UDGHKpTFNOwJuEQztQOiBa5+4TEEFdxpm/+CHOj/NucsDZPWMFWqPRohQeE8UrEgZBfKkom+U4hV8rPLkmQ5IRNRBXFlZsUekAPC+roGNvTZHqAYQt1Uk7wMGNzx+HN/5xk0iHST80/tfGwyn7c90N2BbbHs/jP2IrVC0S8cBU3v2Wd6qnk5eMPBfs6j1lasJY2r9TMftRlcKiH9B84/KkJGTBjrA7XP96C2InivYdsrBFF9xTYeSBdIWx4H0DjZRRtMmpRtWPLu9sLbKLjxzjvdOV/I0rfpdM9p7Hlz5rJzcvHN3ef5jJ1b2LF1sdP1mBqS9niK6vZoNtQYx5g3a8UXXnzwABy9Ba8QJkxJ++rgIVwhwpRhX0hA8lvnmq0bfwEAAP//AwBQSwMEFAAGAAgAAAAhALbhLx82AwAADQgAAA0AAAB4bC9zdHlsZXMueG1spFXNjtMwEL4j8Q6W71kn2aa0VZIV3W4kJJCQdpG4uonTWvgnctwlBXHmwDvwDhw58A67b8Q4P21WLOxqubT2ePz5m/lmJvFZIwW6ZqbmWiU4OPExYirXBVebBL+7yrwZRrWlqqBCK5bgPavxWfr8WVzbvWCXW8YsAghVJ3hrbbUgpM63TNL6RFdMwUmpjaQWtmZD6sowWtTukhQk9P0pkZQr3CEsZP4YEEnNh13l5VpW1PI1F9zuWyyMZL54tVHa0LUAqk0woTlqgqkJUWOGR1rrH+9Inhtd69KeAC7RZclz9ifdOZkTmh+RAPlpSEFE/PBO7I15ItKEGHbNnXw4jUutbI1yvVM2wSEQdSlYfFD6o8rcESjce6Vx/QldUwGWAJM0zrXQBlmQDjLXWhSVrPM4p4KvDXduJZVc7Dtz6Ayt2r2f5JB7ZySOR8cmjdfO685bj0PuQdq/GsC4EKPQOkMaQw1YZlQGp6hfX+0riEFBuXZc4OhB742h+yCMRhdI+yDQ16aA9jgmdTClsWClheAM32zdv9UV/K61tVBCaVxwutGKCpePDuTuTWgr6KAE2y10wCAA3Vnd5584+B79Qd+WQ0vhQVegObB80LcL5v5Y+qBAmpwJcemCeV8e8uTqrCmR2slM2ldFgmGwuKoYliBKv+xy021crsZoHfYINnwSLGrKA/7fSAXA7z5SYB9uI1pVYu8ayUnU7ZZteRz3LwXfKMk6lzSGzum2aKsN/wRXXcvlcM5gIsHctTx3FhClrb2m7DMAMY8SeyethwQh10gJvvl+8+P22+3Xm1+3325+juiud1xYru5JLWAXzVEs371t3dRsZTy8BpoVrKQ7Ya8Ohwk+rt+wgu/k/OD1ll9r20Ik+Lh+7fojmLo3WGNf11DU8I92hif488XyxXx1kYXezF/OvMkpi7x5tFx50eR8uVplcz/0z7+MZvd/TO72UwNVGUwWtYD5bvpg+xAvj7YEjzYd/VYdoD3mPg+n/sso8L3s1A+8yZTOvNn0NPKyKAhX08nyIsqiEffoiRPeJ0HQfSsc+WhhuWSCq0GrQaGxFUSC7T+CIIMS5PgdT38DAAD//wMAUEsDBBQABgAIAAAAIQBKqgGQQAIAADUFAAAUAAAAeGwvc2hhcmVkU3RyaW5ncy54bWyEVF1rE1EQfRf8D5d9UrDZtIKIbDYPgr9Af8CSrE0g2Y25G9G37EZTsUJLEQRRW4Pga1IbsuTzL8z8I89c0ka7m/Ypm73nzpxz5sw65TfNhnrtt3U9DErWbqFoKT+ohNV6sF+yXjx/tvPYUjrygqrXCAO/ZL31tVV2795xtI4U7ga6ZNWiqPXEtnWl5jc9XQhbfoCTl2G76UX42963davte1Vd8/2o2bD3isVHdtOrB5aqhJ0gKll76NIJ6q86/tOrF66j664TuXTCXRrTnI8UrWhJFzTkA0oVDeinogUNFU1oSH+4yz08Tbnn2JHr2HJ7XeEHTQFcKjrnww2Q0gzwKy055kRxHx0XnHA3W4sTWoHRkM4pxfOYZvwpgzoF0Rn3QHS4FXNMF6KM42sCcnhtoKbz5EYRA0pppa4gS1HN7xXNpRcnOe6M+KM4LP7OIGzxAOCH6p44fD/PI5rtQD38XJfcBh2YyY0wlzG8jGWCM5ncKZ3RWTlT+TfMivlQGY0jjCLhwxvbjxGGFJNNua9gM5SiAkaTe2kubGWoBpPmuPzNnEwlUVCeKfIdDURw99ZjyQc4od1qCxlDA1nNU3iMgUGMstENcviDJDtnbgM4dIBkg+5/wJyWn00MAfxngTL6vmD0qEYTWS+aZs7Xubqt1y/Q6hpG2KO12fxOKoJEH7/ZtZOcIHYcCz+oTWStJS1TYzlMNEM+ylA6Md+D7WuIfb7MqlnFWDKyTdjlF+T6whR2NzdsfPbcvwAAAP//AwBQSwMEFAAGAAgAAAAhADn3Q6lHAQAAYAIAABEACAFkb2NQcm9wcy9jb3JlLnhtbCCiBAEooAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIySXWvDIBSG7wf7D8H7xCT9GpKk0JVerTBYx8buRE9badSgbmn+/UzSZhndxS71vOfxOQez5VmWwRcYK7TKURLFKADFNBfqkKPX3SZ8QIF1VHFaagU5asCiZXF/l7GKMG3g2egKjBNgA09SlrAqR0fnKoKxZUeQ1EY+oXxxr42kzh/NAVeUnegBcBrHcyzBUU4dxS0wrAYiuiA5G5DVpyk7AGcYSpCgnMVJlOCfrAMj7Z8NXWWUlMI1lZ/pojtmc9YXh/TZiiFY13VUTzoN75/g9+3TSzdqKFS7KwaoyDgjzAB12hQZHh/84kpq3dbveC+Ar5pi7d8yTbDSRtiTUBm+jXhcZ98zgQfeh/T218rb5HG926AijdNZGC/C9GGXzMlsSqbzj9bgV3/r11/Ii8c/iQsyWZB4TLwC/Jg3f6L4BgAA//8DAFBLAwQUAAYACAAAACEAoGIFep4BAAAbAwAAEAAIAWRvY1Byb3BzL2FwcC54bWwgogQBKKAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACckk1u2zAQhfcFegeB+5hyWgSFQTEonBZZNKgBO9lPqZFFVCIJciLY3bXbHqEX6THiG2UkIY7cZNXd/Dy8+Tgcdblrm6zDmKx3hZjPcpGhM760bluI283nsw8iSwSuhMY7LMQek7jUb9+oVfQBI1lMGVu4VIiaKCykTKbGFtKM2447lY8tEKdxK31VWYNX3ty36Eie5/mFxB2hK7E8C0dDMTouOvpf09Kbni/dbfaBgbX6GEJjDRC/Ut9YE33yFWU3YKwjn+rs085go+RUpphzjeY+WtrrXMlpqtYGGlzyCF1Bk1DJ54K6RujXtwIbk1YdLTo05GOW7A9e4LnIvkHCHqwQHUQLjhiwl43JEDchUdQPfx7+Hn4efh1+K8mCsTiEU+00tu/1fBBwcCrsDUYQbpwibiw1mL5WK4j0CvF8SjwwjLwjzrpGpHHmlG94Mk/6x3vp2wBuz41j9MW67+k2bPwVED6t87So1jVELPkHjus+FtQ1bzI2vcmyBrfF8knzstGfwd1463p+Mcvf5fyvk5qSz1etHwEAAP//AwBQSwECLQAUAAYACAAAACEAYu6daF4BAACQBAAAEwAAAAAAAAAAAAAAAAAAAAAAW0NvbnRlbnRfVHlwZXNdLnhtbFBLAQItABQABgAIAAAAIQC1VTAj9AAAAEwCAAALAAAAAAAAAAAAAAAAAJcDAABfcmVscy8ucmVsc1BLAQItABQABgAIAAAAIQBopRQ+xwIAAFMGAAAPAAAAAAAAAAAAAAAAALwGAAB4bC93b3JrYm9vay54bWxQSwECLQAUAAYACAAAACEAgT6Ul/MAAAC6AgAAGgAAAAAAAAAAAAAAAACwCQAAeGwvX3JlbHMvd29ya2Jvb2sueG1sLnJlbHNQSwECLQAUAAYACAAAACEAPC913RsEAABKDgAAGAAAAAAAAAAAAAAAAADjCwAAeGwvd29ya3NoZWV0cy9zaGVldDEueG1sUEsBAi0AFAAGAAgAAAAhAMKH2/J9BgAA1xsAABMAAAAAAAAAAAAAAAAANBAAAHhsL3RoZW1lL3RoZW1lMS54bWxQSwECLQAUAAYACAAAACEAtuEvHzYDAAANCAAADQAAAAAAAAAAAAAAAADiFgAAeGwvc3R5bGVzLnhtbFBLAQItABQABgAIAAAAIQBKqgGQQAIAADUFAAAUAAAAAAAAAAAAAAAAAEMaAAB4bC9zaGFyZWRTdHJpbmdzLnhtbFBLAQItABQABgAIAAAAIQA590OpRwEAAGACAAARAAAAAAAAAAAAAAAAALUcAABkb2NQcm9wcy9jb3JlLnhtbFBLAQItABQABgAIAAAAIQCgYgV6ngEAABsDAAAQAAAAAAAAAAAAAAAAADMfAABkb2NQcm9wcy9hcHAueG1sUEsFBgAAAAAKAAoAgAIAAAciAAAAAA==""".strip()

# === Logging ===
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# === Init bot ===
session = AiohttpSession()
bot = Bot(token=API_TOKEN, session=session)
dp = Dispatcher()

# === Колонки-мэппинг ===
COLUMN_MAPPING = {
    "Время подачи ТС на загрузку": "Время подачи ТС на загрузку",
    "Окно выгрузки": "Время подачи ТС на разгрузку",
    "Кост центр": "Внутренний заказчик",
    "Отправитель": "Организация отправитель",
    "Получатель": "Организация получатель",
    "Адрес загрузки": "Адрес загрузки",
    "Адрес разгрузки": "Адрес разгрузки",
    "Объем план, м3 (ТС)": "Объем, куб м",
    "Кол-во мест (ТС)": "Кол-во грузовых мест",
    "Требуется ли ПРР?": "Требуется ли погрузка",
    "Часы работы": "Часы работы",
    "Кол-во единиц товара": "Количество единиц товара",
    "Комментарии": "Комментарии",
    "Тип маршрута": "направление",
}

# === Подготовка шаблона ===
def load_template():
    decoded = base64.b64decode(EXCEL_TEMPLATE_BASE64)
    with BytesIO(decoded) as b:
        return pd.read_excel(b)

def clean_string(value):
    if pd.isna(value):
        return ""
    return str(value).strip().replace('\xa0', '').replace('\u200b', '').replace('  ', ' ')

def parse_driver_and_phone(value):
    clean_val = clean_string(value)
    if not clean_val:
        return ""
    parts = [x.strip() for x in clean_val.split(",")]
    if len(parts) >= 2:
        return f"{parts[0]}, {parts[1]}"
    return parts[0]

@dp.message(F.document)
async def handle_doc(message: Message):
    logger.info(f"📥 Получен файл от {message.from_user.username}")
    file = await bot.download(message.document)
    incoming_df = pd.read_excel(file)
    incoming_df = incoming_df.applymap(clean_string)

    template_df = load_template()
    output_df = pd.DataFrame(columns=template_df.columns)

    for col in output_df.columns:
        if col == "Тип грузовых мест":
            output_df[col] = ""
        elif col == "Контакты":
            output_df[col] = incoming_df.get("Контакты", "").map(parse_driver_and_phone)
        elif col == "Водитель":
            output_df[col] = ""
        elif col in COLUMN_MAPPING:
            source_col = COLUMN_MAPPING[col]
            output_df[col] = incoming_df.get(source_col, "")
        else:
            output_df[col] = ""

    # Сохранение
    with BytesIO() as b:
        output_df.to_excel(b, index=False)
        b.seek(0)
        processed = BufferedInputFile(b.read(), filename="output.xlsx")
        await message.reply_document(processed)

# === Webhook setup ===
async def on_startup(bot: Bot) -> None:
    await bot.set_webhook(WEBHOOK_URL)
    logger.info(f"🚀 Webhook установлен: {WEBHOOK_URL}")

def main():
    app = web.Application()
    SimpleRequestHandler(dispatcher=dp, bot=bot).register(app, path=WEBHOOK_PATH)
    setup_application(app, dp, bot=bot)
    web.run_app(app, port=8080)

if __name__ == "__main__":
    main()