name: Build Installer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install pandas openpyxl pyinstaller

    - name: Build EXE
      run: |
        pyinstaller --onefile shuffle-rows-xlsx.py

    - name: Install Inno Setup
      run: choco install innosetup -y

    - name: Build Installer
      run: |
        & 'C:\Program Files (x86)\Inno Setup 6\ISCC.exe' 'inno_setup.iss'

    - name: Upload Installer
      uses: actions/upload-artifact@v4
      with:
        name: Setup_ShuffleRowsXlsx
        path: Output/Setup_ShuffleRowsXlsx.exe